Experiment-13

Data Binning and Data Formation Using Python

Ashman V. Aiyer

PRN-25070123025

ENTC-A2

In [ ]:
import pandas as pd
import numpy as np
data={
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15]
}

df=pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#Data Binning
bins1=[0,10000,30000,60000]
labels1=['Low','Medium','High']
df['Price_Category']=pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [ ]:
#Binning Units Sold
bins1=[0,30,60,100]
labels1=['Less sale','Moderate sale','High sale']
df['Sales_Category']=pd.cut(df['Units_Sold'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Less sale
1      Mobile  20000          60         Medium  Moderate sale
2      Tablet  30000          35         Medium  Moderate sale
3  Headphones   2000          80            Low      High sale
4  Smartwatch   8000          50            Low  Moderate sale
5      Camera  45000          15           High      Less sale

In [ ]:
#Data Formatting
#Convert Data Type
print(df.dtypes)
df['Price']=df['Price'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price              float64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

In [ ]:
#Convert Text to Uppercase
df['Product']=df['Product'].str.upper()
print(df)

      Product    Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000.0          25           High      Less sale
1      MOBILE  20000.0          60         Medium  Moderate sale
2      TABLET  30000.0          35         Medium  Moderate sale
3  HEADPHONES   2000.0          80            Low      High sale
4  SMARTWATCH   8000.0          50            Low  Moderate sale
5      CAMERA  45000.0          15           High      Less sale

In [ ]:
#Rounding Values
df['Price']=df['Price'].round(2)
print(df)

      Product    Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000.0          25           High      Less sale
1      MOBILE  20000.0          60         Medium  Moderate sale
2      TABLET  30000.0          35         Medium  Moderate sale
3  HEADPHONES   2000.0          80            Low      High sale
4  SMARTWATCH   8000.0          50            Low  Moderate sale
5      CAMERA  45000.0          15           High      Less sale

In [ ]:
#Additional Operations
#Sort Data
sorted_df=df.sort_values(by='Price')
print(sorted_df)

      Product    Price  Units_Sold Price_Category Sales_Category
3  HEADPHONES   2000.0          80            Low      High sale
4  SMARTWATCH   8000.0          50            Low  Moderate sale
1      MOBILE  20000.0          60         Medium  Moderate sale
2      TABLET  30000.0          35         Medium  Moderate sale
5      CAMERA  45000.0          15           High      Less sale
0      LAPTOP  55000.0          25           High      Less sale

In [ ]:
#Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
#Dataset: Food Delivery Orders
import pandas as pd
import numpy as np
data={
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_km':[5,8,3,10,6,2,9,4]
}
df=pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [ ]:
#Binning Order Value
bins=[0,200,400,700]
labels=['Low Order','Medium Order','High Order']
df['Order_Category']=pd.cut(df['Order_Value'],bins=bins,labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [ ]:
#Binning Delivery Time
bins2=[0,30,45,70]
labels2=['Fast','Normal','Slow']
df['Delivery_Speed']=pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

  Delivery_Speed
0           Fast
1         Normal
2           Fast
3           Slow
4         Normal
5           Fast
6           Slow
7           Fast

In [ ]:
#Data Formatting Examples
#Convert Distance to Float
df['Distance_km']=df['Distance_km'].astype(float)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30          5.0   Medium Order
1       02          450             45          8.0     High Order
2       03          120             25          3.0      Low Order
3       04          600             60         10.0     High Order
4       05          300             35          6.0   Medium Order
5       06          150             20          2.0      Low Order
6       07          500             50          9.0     High Order
7       08          220             28          4.0   Medium Order

  Delivery_Speed
0           Fast
1         Normal
2           Fast
3           Slow
4         Normal
5           Fast
6           Slow
7           Fast

In [ ]:
#Convert Order_Category to Uppercase
df['Order_Category']=df['Order_Category'].str.upper()
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30          5.0   MEDIUM ORDER
1       02          450             45          8.0     HIGH ORDER
2       03          120             25          3.0      LOW ORDER
3       04          600             60         10.0     HIGH ORDER
4       05          300             35          6.0   MEDIUM ORDER
5       06          150             20          2.0      LOW ORDER
6       07          500             50          9.0     HIGH ORDER
7       08          220             28          4.0   MEDIUM ORDER

  Delivery_Speed
0           Fast
1         Normal
2           Fast
3           Slow
4         Normal
5           Fast
6           Slow
7           Fast

In [ ]:
#Check Data Types
print(df.dtypes)

Order_ID            object
Order_Value          int64
Delivery_Time        int64
Distance_km        float64
Order_Category      object
Delivery_Speed    category
dtype: object

In [ ]:
#Unique Categories
print(df['Order_Category'].unique())
df

['MEDIUM ORDER' 'HIGH ORDER' 'LOW ORDER']

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Speed
0,01,250,30,5.0,MEDIUM ORDER,Fast
1,02,450,45,8.0,HIGH ORDER,Normal
2,03,120,25,3.0,LOW ORDER,Fast
3,04,600,60,10.0,HIGH ORDER,Slow
4,05,300,35,6.0,MEDIUM ORDER,Normal
5,06,150,20,2.0,LOW ORDER,Fast
6,07,500,50,9.0,HIGH ORDER,Slow
7,08,220,28,4.0,MEDIUM ORDER,Fast

In [ ]:
#Count of categories
print(df['Order_Category'].value_counts())
df

Order_Category
MEDIUM ORDER    3
HIGH ORDER      3
LOW ORDER       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Speed
0,01,250,30,5.0,MEDIUM ORDER,Fast
1,02,450,45,8.0,HIGH ORDER,Normal
2,03,120,25,3.0,LOW ORDER,Fast
3,04,600,60,10.0,HIGH ORDER,Slow
4,05,300,35,6.0,MEDIUM ORDER,Normal
5,06,150,20,2.0,LOW ORDER,Fast
6,07,500,50,9.0,HIGH ORDER,Slow
7,08,220,28,4.0,MEDIUM ORDER,Fast

In [ ]:
#Sorting
sorted_df=df.sort_values(by='Order_Value')
print(sorted_df)
df

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
2       03          120             25          3.0      LOW ORDER
5       06          150             20          2.0      LOW ORDER
7       08          220             28          4.0   MEDIUM ORDER
0       01          250             30          5.0   MEDIUM ORDER
4       05          300             35          6.0   MEDIUM ORDER
1       02          450             45          8.0     HIGH ORDER
6       07          500             50          9.0     HIGH ORDER
3       04          600             60         10.0     HIGH ORDER

  Delivery_Speed
2           Fast
5           Fast
7           Fast
0           Fast
4         Normal
1         Normal
6           Slow
3           Slow

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Speed
0,01,250,30,5.0,MEDIUM ORDER,Fast
1,02,450,45,8.0,HIGH ORDER,Normal
2,03,120,25,3.0,LOW ORDER,Fast
3,04,600,60,10.0,HIGH ORDER,Slow
4,05,300,35,6.0,MEDIUM ORDER,Normal
5,06,150,20,2.0,LOW ORDER,Fast
6,07,500,50,9.0,HIGH ORDER,Slow
7,08,220,28,4.0,MEDIUM ORDER,Fast